### ISSUE TITLE
[auto-skip-epic] expand supported commands

### ISSUE THREAD

**Issue by alexcb** [earthly/earthly#2968]
not all Earthfile commands effect the auto-skip hash, as a result some Earthfiles can't use auto-skip even thought they don't require shelling out.
```[tasklist]
### Tasks
- [ ] https://github.com/earthly/earthly/issues/3040
- [ ] https://github.com/earthly/earthly/issues/3042
- [ ] https://github.com/earthly/earthly/issues/3045
- [ ] https://github.com/earthly/earthly/issues/3043
- [ ] https://github.com/earthly/earthly/issues/3046
- [ ] https://github.com/earthly/earthly/issues/3044
```

**Comment by alexcb** [comment]
Additionally non-shell-out args need to be supported.
