### ISSUE TITLE
Update Syntax Highlighting for IDE/editor plugins

### ISSUE THREAD

**Issue by Velutas** [earthly/earthly#3134]
```[tasklist]
### Tasks
- [x] update vscode syntax
- [x] update git syntax
- [x] update intellij syntax
- [x] update vim syntax
- [x] update sublime text syntax
- [x] update emacs syntax
```
