### ISSUE TITLE
Podman support

### ISSUE THREAD

**Issue by lpil** [earthly/earthly#760]
Hello! This is a very cool project, I'm excited to give it a try

I use [podman](https://podman.io/), Red Hat's drop-in replacement for docker that is easier to install, doesn't require root, and is more secure.
Is it possible to use Earthly with podman? In the installation instructions it explicitly says docker is required.

Does Earthly talk to the docker daemon itself? If it uses the docker command line interface podman may "just work".

Thanks,
Louis

**Comment by lpil** [comment]
```shell
❯ ln -s /usr/bin/podman docker

❯ docker
Error: missing command 'podman COMMAND'
Try 'podman --help' for more information.
error: External command failed

❯ earthly github.com/earthly/hello-world:main+hello
           buildkitd | Starting buildkit daemon as a docker container (earthly-buildkitd)...
           buildkitd | Is docker installed and running? Are you part of the docker group?
Error: buildkitd new client: buildkitd new client (own): maybe start buildkitd: start: compatibility: failed compatibilty check: get docker security info: exit status 125
```

Alas, while it does use the CLI it doesn't work due to an explicit check.

**Comment by alexcb** [comment]
Does running earthly with the verbose and debugging flags give any extra information? 

Can you try running `earthly -VD github.com/earthly/hello-world:main+hello`; followed by checking the `earthly-buildkitd` container for any additional logs: `docker logs earthly-buildkitd`

**Comment by dchw** [comment]
Hi @lpil! That is indeed part of our compatibility checking, which invokes a series of `docker security` commands. Podman has no such commands.

We use it to check for instances when people are running `docker` with User Namespaces, or in Rootless mode. Both of those modes prohibit privileged containers, which we use to run docker-in-docker. That said, it looks like there is additional incompatibility when tose checks are bypassed:

```
           buildkitd | Starting buildkit daemon as a docker container (earthly-buildkitd)...
           buildkitd | Is docker installed and running? Are you part of the docker group?
Error: buildkitd new client: buildkitd new client (own): maybe start buildkitd: start: docker run earthly/buildkitd:prerelease: Error: invalid reference format
: exit status 125
```

For reference, if you specify additional arguments to use when launching the container, it bypasses the compatibility checks. I use this in `~/.earthly/config.yml` to bypass it:

```
global:
  buildkit_additional_args: ["--log-opt"] # Just some throwaway option to bypass checks
```

**Comment by lpil** [comment]
@alexcb Here is the output of those commands

```
❯ earthly -VD github.com/earthly/hello-world:main+hello
           buildkitd | Starting buildkit daemon as a docker container (earthly-buildkitd)...
           buildkitd | Is docker installed and running? Are you part of the docker group?
Error: buildkitd new client: buildkitd new client (own): maybe start buildkitd: start: compatibility: failed compatibilty check: get docker security info: exit status 125
Warning: timedout while sending analytics
error while sending analytics to earthly: failed to send analytics: Put "https://api.earthly.dev/analytics": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

```
❯ docker logs earthly-buildkitd
Error: no container with name or ID earthly-buildkitd found: no such container
```

**Comment by vladaionescu** [comment]
I think it may be possible to implement support for podman at some point. I'll turn this issue into a proposal and put it in the roadmap to see if it gains traction to prioritize it.

**Comment by lpil** [comment]
Thank you

**Comment by dchw** [comment]
Little bit more info I found when investigating if it were possible after the compatibility checks:

Running it directly gives the following:
```
starting earthly-buildkit with EARTHLY_GIT_HASH=857fb8ab003e642dfcd9217c56c6d06ce3e5d137 BUILDKIT_BASE_IMAGE=github.com/earthly/buildkit:earthly-main+build
BUILDKIT_ROOT_DIR=/tmp/earthly/buildkit
CACHE_SIZE_MB=0
EARTHLY_ADDITIONAL_BUILDKIT_CONFIG=
======== Buildkitd config ==========
debug = false
root = "/tmp/earthly/buildkit"
insecure-entitlements = [ "security.insecure" ]

[worker.oci]
  enabled = true
  snapshotter = "auto"
  gc = true
  networkMode = "cni"
  cniBinaryPath = "/usr/libexec/cni"
  cniConfigPath = "/etc/cni/cni-conf.json"
  


======== End buildkitd config ==========
Detected container architecture is x86_64
starting shellrepeater
time="2021-02-04T19:23:50Z" level=info msg="auto snapshotter: using native"
buildkitd: operation not permitted
Error: buildkit process has exited
```

And running it with `podman`s `--privileged`:
```
❯ docker run --privileged earthly/buildkitd:prerelease
Error: container_linux.go:370: starting container process caused: unknown capability "CAP_PERFMON": OCI runtime error
```
But it will start when `podman` is invoked with `sudo`, implying its some additional permissions things.

**Comment by vladaionescu** [comment]
Ah interesting - indeed it seems to be tied to privileged mode. Perhaps a rootless mode would allow it to work.

> "auto snapshotter: using native"

If it doesn't automatically switch to overlayfs with privileged or rootless, we can try to force it. Native can get extremely slow.

**Comment by MLNW** [comment]
I would love to see support for podman. It is much simpler to use with WSL2 compared to docker, which needs software installed on the host operating system.

**Comment by diegobernardes** [comment]
With the new terms of usage of Docker, the support for Podman is something critical for the adoption of Earthly by companies.

https://www.docker.com/blog/updating-product-subscriptions/

**Comment by vladaionescu** [comment]
Agreed

**Comment by dchw** [comment]
We've added experimental support for Podman. You can enable it by explicitly setting it in your configuration, like this `earthly config global.container_frontend podman-shell`.

**Comment by vladaionescu** [comment]
This can be promoted to Beta, except that there is one key issue we could improve. Sometimes the initialization errors are misleading. For example...

```
loading config values from "/etc/.earthly/config.yml"
auto frontend initialization failed due to failed to autodetect a supported frontend: 2 errors occurred:
	* docker-shell frontend failed to initalize: command failed: docker info: exit status 1: Client:
 Context:    default
 Debug Mode: false

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info: exit status 1
	* podman-shell frontend failed to initalize: command failed: podman info --format={{.Host.Security.Rootless}}: exec: "podman": executable file not found in $PATH: : exec: "podman": executable file not found in $PATH

; but will try anyway
Local registry host is specified while using remote buildkit. Local registry will not be used.

 1. Init 🚀
————————————————————————————————————————————————————————————————————————————————
```

**Comment by vladaionescu** [comment]
Beta to GA might possibly require more extensive tests to run in GHA. (e.g. uninstall docker, then install podman and run most of our existing tests)

**Comment by r-LaForge** [comment]
related to #1870

**Comment by r-LaForge** [comment]
This proposal is of a sufficient size to break into sub-issues.

The sub-issues are as follows:
 - [ ] Add CI for Podman in this repository #2202 
 - [ ] Add documentation for using Podman #2203
 - [ ] Enable usage of WITH DOCKER with Podman #1870 
 - [ ] #1870 will include investigating the --compose option and evaluating how to proceed. (Can we simply support with docker-compose, or do we need podman-compose)?

**Comment by r-LaForge** [comment]
Exploration of `WITH DOCKER` has been done and is documented in the guide: https://docs.earthly.dev/docs/guides/podman#podman-within-with-docker

The behaviour of using Podman will depend on if you are using `LOCALLY` (running on the host machine) or within the container. If you are using `LOCALLY` you can use `podman-compose` and if you are not you must use `docker-compose`.

With privileged mode still being a [documented requirement](https://docs.earthly.dev/docs/guides/using-the-earthly-docker-images/buildkit-standalone#requirements) of our earthly/dind image we have chosen to defer work on rootless podman support in WITH DOCKER.
While rootless Podman may work for the majority of commands (with the exception of WITH DOCKER) we are not making any guarantees at this time.

If you would like to see that issue looked at sooner please upvote the issue: https://github.com/earthly/earthly/issues/1870

**Comment by alexcb** [comment]
as of earthly `v0.7.0`, podman support is GA.

if you run into any podman-related issues, please open a new ticket specific to your issue.
